controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_forward_controller:
      type: forward_command_controller/ForwardCommandController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_joint
    state_interfaces:
      - position
      - velocity
    command_interfaces:
      - position
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01
      arm_joint:
        trajectory: 0.5
        goal: 0.1

position_forward_controller:
  ros__parameters:
    joints:
      - x_joint
      - y_joint
      - theta_joint
    interface_name: position
    state_interfaces:
      - position
    command_interfaces:
      - position
